# Author: {{cookiecutter.author}} 
# Date Created: {% now 'local', '%m/%d/%Y' %}

# Lints {{cookiecutter.project}} directory recursively
lint:
	pylint {{cookiecutter.project}}

# Type checks {{cookiecutter.project}} directory recursively
type:
	mypy {{cookiecutter.project}}

# Runs all tests in tests directory 
test:
	pytest
